# Generated by Django 4.1.3 on 2022-11-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mashina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rangi', models.TextField()),
                ('rasm', models.CharField(max_length=200)),
            ],
        ),
    ]
